"""
Report generator — produces a Markdown investigation report.
Clearly distinguishes observed facts from detection-rule results from analyst interpretation.
"""
import logging
from datetime import datetime
from sqlalchemy.orm import Session
from app.models.investigation import Investigation
from app.models.alert import Alert
from app.models.record import DNSRecord, HTTPRecord, ICMPRecord
from app.models.host import Host
from app.models.conversation import Conversation
from app.models.ioc import IOC

logger = logging.getLogger(__name__)


def _ts(ts: float | None) -> str:
    if not ts:
        return "N/A"
    try:
        return datetime.utcfromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S UTC")
    except Exception:
        return str(ts)


def _bytes_human(b: int) -> str:
    if b < 1024:
        return f"{b} B"
    elif b < 1024 ** 2:
        return f"{b / 1024:.1f} KB"
    elif b < 1024 ** 3:
        return f"{b / (1024**2):.1f} MB"
    else:
        return f"{b / (1024**3):.2f} GB"


def generate_report(db: Session, investigation_id: int) -> str:
    """Generate a full Markdown investigation report."""
    inv = db.query(Investigation).filter(Investigation.id == investigation_id).first()
    if not inv:
        return "# Error\n\nInvestigation not found."

    alerts = db.query(Alert).filter(Alert.investigation_id == investigation_id).all()
    hosts = db.query(Host).filter(Host.investigation_id == investigation_id).order_by(Host.total_packets.desc()).limit(20).all()
    conversations = db.query(Conversation).filter(Conversation.investigation_id == investigation_id).order_by(Conversation.total_packets.desc()).limit(20).all()
    dns_records = db.query(DNSRecord).filter(DNSRecord.investigation_id == investigation_id, DNSRecord.is_response == 0).limit(100).all()
    http_records = db.query(HTTPRecord).filter(HTTPRecord.investigation_id == investigation_id, HTTPRecord.is_request == 1).limit(50).all()
    icmp_records = db.query(ICMPRecord).filter(ICMPRecord.investigation_id == investigation_id).limit(50).all()
    iocs = db.query(IOC).filter(IOC.investigation_id == investigation_id).order_by(IOC.occurrence_count.desc()).limit(50).all()

    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    high_alerts = [a for a in alerts if a.severity == "high"]
    medium_alerts = [a for a in alerts if a.severity == "medium"]
    low_alerts = [a for a in alerts if a.severity == "low"]

    lines = [
        f"# Nova Cyber Spark — Network Traffic Investigation Report",
        f"",
        f"> **Platform:** Nova Cyber Spark™ Network Traffic Forensics & Cyber Intelligence  ",
        f"> **Founder & Architect:** Pranay Kumar Mallem  ",
        f"> **Investigation ID:** {inv.inv_id}  ",
        f"> **Generated:** {now}  ",
        f"> **Status:** {inv.status.upper()}  ",
        f"> **Analyst:** [Analyst Name]",
        f"",
        f"---",
        f"",
        f"> ⚠️ **DISCLAIMER**: This report is generated by automated analysis tools.",
        f"> Detection rule results represent **heuristic findings** and must be reviewed by",
        f"> a qualified analyst. No finding in this report should be interpreted as proof",
        f"> of compromise without further investigation.",
        f"",
        f"---",
        f"",
        f"## 1. Executive Summary",
        f"",
        f"This report documents the automated analysis of network traffic captured in **{inv.original_filename}**.",
        f"The capture contains **{inv.total_packets:,}** packets representing **{_bytes_human(inv.total_bytes)}** of traffic",
        f"involving **{inv.unique_hosts}** unique network hosts.",
        f"",
        f"The automated detection engine identified **{inv.total_alerts}** potentially suspicious events:",
        f"",
        f"| Severity | Count |",
        f"|----------|-------|",
        f"| 🔴 High | {len(high_alerts)} |",
        f"| 🟠 Medium | {len(medium_alerts)} |",
        f"| 🟡 Low | {len(low_alerts)} |",
        f"| 🔵 Informational | {len([a for a in alerts if a.severity == 'informational'])} |",
        f"",
        f"**All findings require analyst review before any conclusions can be drawn.**",
        f"",
        f"---",
        f"",
        f"## 2. Investigation Objective",
        f"",
        f"Analyze captured network traffic to:",
        f"- Identify network hosts and communication patterns",
        f"- Extract protocol-level details (DNS, HTTP, TCP, ICMP)",
        f"- Apply detection heuristics to identify potentially anomalous behavior",
        f"- Document observed indicators for further investigation",
        f"",
        f"---",
        f"",
        f"## 3. Evidence",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Filename | `{inv.original_filename}` |",
        f"| File Size | {_bytes_human(inv.file_size)} |",
        f"| SHA-256 | `{inv.file_hash or 'N/A'}` |",
        f"| Format | PCAP/PCAPNG |",
        f"| Uploaded | {inv.created_at.strftime('%Y-%m-%d %H:%M:%S UTC') if inv.created_at else 'N/A'} |",
        f"",
        f"---",
        f"",
        f"## 4. PCAP Information",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Total Packets | {inv.total_packets:,} |",
        f"| Total Bytes | {_bytes_human(inv.total_bytes)} |",
        f"| Capture Start | {_ts(float(inv.capture_start) if inv.capture_start else None)} |",
        f"| Capture End | {_ts(float(inv.capture_end) if inv.capture_end else None)} |",
        f"| Duration | {inv.capture_duration:.2f} seconds |",
        f"| Unique Hosts | {inv.unique_hosts} |",
        f"| Total Alerts | {inv.total_alerts} |",
        f"",
        f"---",
        f"",
        f"## 5. Network Overview",
        f"",
        f"The capture includes traffic from {inv.unique_hosts} unique hosts.",
        f"",
        f"### Top Hosts by Packet Count",
        f"",
        f"| IP Address | Role | Total Packets | Total Bytes | Dest IPs |",
        f"|------------|------|--------------|-------------|----------|",
    ]

    for h in hosts[:10]:
        lines.append(f"| {h.ip_address} | {h.role} | {h.total_packets:,} | {_bytes_human(h.total_bytes)} | {h.unique_dest_ips} |")

    lines += [
        f"",
        f"---",
        f"",
        f"## 6. Protocol Analysis",
        f"",
        f"*Protocol distribution is available in the platform's Traffic Analysis view.*",
        f"",
        f"---",
        f"",
        f"## 7. Host Analysis",
        f"",
        f"Total unique hosts observed: **{inv.unique_hosts}**",
        f"",
        f"*See the Hosts page for detailed per-IP analysis.*",
        f"",
        f"---",
        f"",
        f"## 8. Conversation Analysis",
        f"",
        f"### Top Conversations by Packet Count",
        f"",
        f"| Source | Destination | Protocol | Packets | Bytes | Duration |",
        f"|--------|-------------|----------|---------|-------|----------|",
    ]

    for c in conversations[:15]:
        src_ep = f"{c.src_ip}:{c.src_port}" if c.src_port else c.src_ip
        dst_ep = f"{c.dst_ip}:{c.dst_port}" if c.dst_port else c.dst_ip
        lines.append(f"| {src_ep} | {dst_ep} | {c.protocol} | {c.total_packets:,} | {_bytes_human(c.total_bytes)} | {c.duration:.2f}s |")

    lines += [
        f"",
        f"---",
        f"",
        f"## 9. DNS Investigation",
        f"",
        f"Total DNS queries extracted: **{len(dns_records)}** (showing first 20)",
        f"",
        f"| Timestamp | Source | Query | Type |",
        f"|-----------|--------|-------|------|",
    ]

    for r in dns_records[:20]:
        lines.append(f"| {r.timestamp_str or _ts(r.timestamp)} | {r.src_ip or 'N/A'} | `{r.query_name or 'N/A'}` | {r.query_type or 'A'} |")

    lines += [
        f"",
        f"---",
        f"",
        f"## 10. HTTP Investigation",
        f"",
        f"Total HTTP requests extracted: **{len(http_records)}** (showing first 20)",
        f"",
        f"| Timestamp | Source | Method | Host | URI | Status |",
        f"|-----------|--------|--------|------|-----|--------|",
    ]

    for r in http_records[:20]:
        uri_short = (r.uri or "")[:60] + ("..." if len(r.uri or "") > 60 else "")
        lines.append(f"| {r.timestamp_str or _ts(r.timestamp)} | {r.src_ip or 'N/A'} | {r.method or '-'} | {r.host or '-'} | `{uri_short}` | {r.status_code or '-'} |")

    lines += [
        f"",
        f"---",
        f"",
        f"## 11. TCP Investigation",
        f"",
        f"*TCP statistics (SYN/ACK/RST/FIN counts) are available in the platform's TCP view.*",
        f"",
        f"---",
        f"",
        f"## 12. ICMP Investigation",
        f"",
        f"Total ICMP packets: **{len(icmp_records)}**",
        f"",
        f"---",
        f"",
        f"## 13. Potentially Suspicious Activity",
        f"",
        f"> ⚠️ The following findings are produced by automated detection rules.",
        f"> They represent **potential** indicators of suspicious activity.",
        f"> Analyst review is required before drawing conclusions.",
        f"",
    ]

    if not alerts:
        lines.append("No alerts generated for this investigation.")
    else:
        for alert in sorted(alerts, key=lambda a: ["high", "medium", "low", "informational"].index(a.severity) if a.severity in ["high", "medium", "low", "informational"] else 4):
            sev_emoji = {"high": "🔴", "medium": "🟠", "low": "🟡", "informational": "🔵"}.get(alert.severity, "⚪")
            lines += [
                f"### {sev_emoji} {alert.alert_id}: {alert.alert_type}",
                f"",
                f"**Severity:** {alert.severity.upper()}  ",
                f"**Rule:** `{alert.detection_rule}`  ",
                f"**Source:** {alert.src_ip or 'N/A'}  ",
                f"**Destination:** {alert.dst_ip or 'N/A'}  ",
                f"**First Seen:** {_ts(alert.first_seen)}",
                f"",
                f"**What was detected?**",
                f"",
                f"{alert.reason or 'No description available.'}",
                f"",
                f"**Recommended Investigation Steps:**",
                f"",
                f"{alert.recommendations or 'No recommendations available.'}",
                f"",
            ]

    lines += [
        f"---",
        f"",
        f"## 14. Timeline",
        f"",
        f"*The investigation timeline is available in the platform's Timeline view.*",
        f"",
        f"---",
        f"",
        f"## 15. Indicators",
        f"",
        f"> ⚠️ All indicators below are **OBSERVED** in the traffic capture.",
        f"> They are NOT confirmed malicious without threat intelligence enrichment.",
        f"",
        f"| Type | Value | First Seen | Context |",
        f"|------|-------|-----------|---------|",
    ]

    for ioc in iocs[:30]:
        lines.append(f"| {ioc.ioc_type} | `{str(ioc.value)[:80]}` | {ioc.first_seen_str or 'N/A'} | {ioc.context or '-'} |")

    lines += [
        f"",
        f"---",
        f"",
        f"## 16. Findings",
        f"",
        f"*[Analyst fills in their interpreted findings here after reviewing the automated results.]*",
        f"",
        f"---",
        f"",
        f"## 17. Recommended Investigation Steps",
        f"",
        f"Based on the automated analysis:",
        f"",
        f"1. Review all High and Medium severity alerts for false positive determination.",
        f"2. Investigate any flagged hosts in your SIEM for corroborating events.",
        f"3. Enrich extracted domains and IPs against threat intelligence sources.",
        f"4. Check endpoint logs for processes that generated suspicious traffic.",
        f"5. Review firewall and proxy logs for the investigation time window.",
        f"6. If port scanning was detected, check whether the source is an authorized scanner.",
        f"7. For DNS anomalies, check whether queried domains resolve to known malicious IPs.",
        f"",
        f"---",
        f"",
        f"## 18. Conclusion",
        f"",
        f"*[Analyst fills in their conclusion here.]*",
        f"",
        f"This automated report was generated by the Nova Cyber Spark Network Traffic Investigation Engine.",
        f"It is a starting point for investigation, not a final determination.",
        f"",
        f"---",
        f"",
        f"**Nova Cyber Spark™** · *Network Forensic Platform*  ",
        f"**Founder & Architect:** Pranay Kumar Mallem  ",
        f"**Intellectual Property & Patents:** © 2026 Nova Cyber Spark. All Rights Reserved.  ",
        f"*Report generated: {now}* | *Platform version: 2026.1 Enterprise SOC*",
    ]

    return "\n".join(lines)
